services: 
  # Contenedor postgres
  postgres-db: 
    image: postgres
    ports: 
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fundacion_sol
    volumes:
      - pg-data:/var/lib/postgresql/data
  # Contenedor pgadmin4
  pgadmin4:
    image: dpage/pgadmin4
    ports: 
      - "127.0.0.1:5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
  # Contenedor backend (Nest.js)
  backend:
    ports: 
      - "127.0.0.1:3000:3000"
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    links:
     - postgres-db
    volumes:
      - ./backend:/home/app/backend
      - /home/app/backend/node_modules
  # Contenedor frontend (Angular)
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "127.0.0.1:4200:4200"
  #   volumes:
  #     - ./frontend:/home/app/frontend
  #     - /home/app/frontend/node_modules
  #   depends_on:
  #     - backend
# Definir volumenes
volumes:
  pg-data: