services:
  # Contenedor postgres
  postgres-db: 
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=docker
    volumes:
      - pg-data:/var/lib/postgresql/data
  # Contenedor pgadmin4
  pgadmin4:
    image: dpage/pgadmin4
    ports: 
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
  # Contenedor backend (Nest.js)
  backend:
    ports: 
      - "3000:3000"
    build: ./backend
    links:
     - postgres-db
  # Contenedor frontend (Angular)
  frontend:
    build: ./frontend
    ports:
      - "4200:4200" 
    volumes:
      - ./frontend:/home/app
    depends_on:
      - backend
# Definir volumenes
volumes:
  pg-data: