services:

  # Contenedor postgres

  postgres-db:
    image: postgres:17
    env_file:
      - ./.env
    ports:
      - '127.0.0.1:5432:5432'
    container_name: postgres-fundacion-sol
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - pg-data-fundacion-sol:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h postgres-db -U root -p 5432']
      interval: 10s
      timeout: 5s
      retries: 5    

  # Contenedor pgadmin4

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - '127.0.0.1:5050:80'
    container_name: pgadmin4-fundacion-sol
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

  # Contenedor backend (Nest.js)
  
  backend:
    ports:
      - '127.0.0.1:3000:3000'
    container_name: backend-fundacion-sol
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      postgres-db:
        condition: service_healthy
    volumes:
      - ./backend:/home/app/backend
      - /home/app/backend/node_modules
      ##############################- ./const:/home/app/const


volumes:
  pg-data-fundacion-sol:
