name: fundacion-sol


services:

  # Contenedor postgres

  postgres-db:
    image: postgres:17
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - pg-data-fundacion-sol:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h postgres-db -U root -p 5432']
      interval: 10s
      timeout: 5s
      retries: 5    

  # Contenedor pgadmin4

  #pgadmin4:
  #  image: dpage/pgadmin4:9.1.0
  #  ports:
  #    - '5050:80'
  #  container_name: pgadmin4-fundacion-sol
  #  environment:
  #    PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
  #    PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
  
  # Contenedor backend (Nest.js)

  backend:
    #image: backend-fundacion-sol
    ports:
      - '3000:3000'
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      postgres-db:
        condition: service_healthy
    volumes:
      - volumen_compartido:/home/app/backend/frontend

  # Contenedor frontend (Angular)

  frontend:
    #image: frontend-fundacion-sol
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - volumen_compartido:/home/app/frontend/dist
    # SACAR!!!:
    ################command: npm run build -- --output-path=/home/app/frontend/dist

#  && npm run migracion:generar --name=$npm_config_name && npm run migracion:ejecutar !!!!!!!!!!!!!!!!
# Definir volumenes
volumes:
  pg-data-fundacion-sol:
  volumen_compartido: