name: fundacion-sol


services:

  # Contenedor postgres

  postgres-db:
    image: postgres:17
    env_file:
      - ./.env
    #ports:
    #  - '5432:5432'
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - pg-data-fundacion-sol:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h postgres-db -U root -p 5432']
      interval: 10s
      timeout: 5s
      retries: 5    
    networks:
      - webnet

  # Contenedor backend (Nest.js)

  backend:
    ports:
      - '3000:3000'
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      postgres-db:
        condition: service_healthy
    volumes:
      - volumen_compartido:/home/app/backend/frontend
    networks:
      - webnet

  # Contenedor frontend (Angular)

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - volumen_compartido:/home/app/frontend/dist

  # Contenedor nginx

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '3000:3000'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    #environment:
    #  # Postgres parameters:
    #  DB_POSTGRES_HOST: 'postgres-db'
    #  DB_POSTGRES_PORT: '5432'
    #  DB_POSTGRES_USER: ${PG_USERNAME}
    #  DB_POSTGRES_PASSWORD: ${PG_PASSWORD}
    #  DB_POSTGRES_NAME: 'npm'
    #  # Uncomment this if IPv6 is not enabled on your host
    #  # DISABLE_IPV6: 'true'
networks:
  webnet:
    driver: bridge

# Definir volumenes
volumes:
  pg-data-fundacion-sol:
  volumen_compartido: