# Usar una imagen base de Node.js
FROM node:22

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /home/app/backend

# Copiar solo package y package lock.json
COPY package*.json ./

# Instalar las dependencias del proyecto
RUN npm ci

# Instalar nodemon globalmente
RUN npm i -g nodemon

# Copiar los archivos del proyecto al contenedor
COPY . .

# Exponer el puerto 3000
EXPOSE 3000

# Ejecutar la aplicación en modo desarrollo
CMD ["npm", "run", "start:dev"]
